### ISSUE TITLE
cannot install on mac

### ISSUE THREAD

**Issue by wyclyne** [balle/Net-ARP#1]
"/usr/bin/perl" "/System/Library/Perl/5.18/ExtUtils/xsubpp"  -typemap '/System/Library/Perl/5.18/ExtUtils/typemap'  ARP.xs > ARP.xsc
Please specify prototyping behavior for ARP.xs (see perlxs manual)
mv ARP.xsc ARP.c
cc -c   -arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"1.0.8\" -DXS_VERSION=\"1.0.8\"  "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"  -DBSD ARP.c
In file included from ARP.xs:24:
./ppport.h:221:11: warning: 'PERL_UNUSED_DECL' macro redefined [-Wmacro-redefined]
#  define PERL_UNUSED_DECL
          ^
/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/perl.h:320:13: note: previous
      definition is here
#    define PERL_UNUSED_DECL __attribute__unused__
            ^
ARP.xs:30:10: fatal error: 'netinet/ether.h' file not found
#include <netinet/ether.h>
         ^~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [ARP.o] Error 1

**Comment by balle** [comment]
Hi, 

that's correct. Only Linux and FreeBSD are supported yet.

Best,

Basti


Am Tue, 02 Jan 2018 09:48:55 +0000 (UTC)
schrieb wyclyne <notifications@github.com>:

> "/usr/bin/perl" "/System/Library/Perl/5.18/ExtUtils/xsubpp"  -typemap
> '/System/Library/Perl/5.18/ExtUtils/typemap'  ARP.xs > ARP.xsc Please
> specify prototyping behavior for ARP.xs (see perlxs manual) mv
> ARP.xsc ARP.c cc -c   -arch x86_64 -arch i386 -g -pipe -fno-common
> -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os
> -DVERSION=\"1.0.8\" -DXS_VERSION=\"1.0.8\"
> "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"  -DBSD
> ARP.c In file included from ARP.xs:24: ./ppport.h:221:11: warning:
> 'PERL_UNUSED_DECL' macro redefined [-Wmacro-redefined] #  define
> PERL_UNUSED_DECL
> ^ /System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/perl.h:320:13:
> note: previous definition is here #    define PERL_UNUSED_DECL
> __attribute__unused__ ^ ARP.xs:30:10: fatal error: 'netinet/ether.h'
> file not found #include <netinet/ether.h>
>          ^~~~~~~~~~~~~~~~~
> 1 warning and 1 error generated.
> make: *** [ARP.o] Error 1
> 
>

**Comment by balle** [comment]
Hi,
I know long time ago, but maybe I now found a fix for the compilation problem. Could you try this branch? https://github.com/balle/Net-ARP/tree/macos-compile-1
Best,
Basti
